version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    command: --wiredTigerCacheSizeGB 1.5

  redis:
    image: redis:7.0.11-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --loglevel warning
    volumes:
      - redis-data:/data
    
volumes:
  mongo-data:
  redis-data:
