name: Create a Docker Image and publish it to Github registry

on:
  workflow_dispatch:
  push:
    branches:
      - 'develop'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  bump-new-release:
    name: Update release
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config -l

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - run: npm ci
  
      - run: npm run release -- -VV
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASEIT_TOKEN }}

  build-and-push-image:
    runs-on: ubuntu-latest
    needs: bump-new-release
    environment: stage

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./deploy/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Create Drone build for stage
        run: |
          curl -X POST "${{ vars.DRONE_HOST }}/api/repos/${{ github.repository }}/builds?branch=${{ github.ref_name }}&commit=${{ github.sha }}" -H "Authorization: Bearer ${{ secrets.DRONE_TOKEN }}"
