name: On Pull Request

on:
  pull_request:
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test
      
      - name: Rin lint
        run: npm run lint

  integration-tests:
    needs: unit-tests
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-db: test

      - name: Start Redis
        uses: supercharge/redis-github-action@1.6.0

      - name: Run tests
        run: npm run test:e2e
        env:
          APP_NAME: 'AirBnB3'
          APP_PORT: 3000
          MONGODB_URI: 'mongodb://localhost:27017'
          MONGODB_DBNAME: 'test'
          JWT_SECRET: 'secret'
          JWT_ACCESS_EXPIRE: 1d
          TELEGRAM_TEMPLATE_DIR: 'resources/templates/telegram'
            