name: On Pull Request

on:
  workflow_dispatch:
  pull_request:
    branches-ignore: 
      - 'ci/*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    if: (startsWith( github.head_ref, 'ci/' ) || startsWith( github.head_ref, 'doc/' )) == false
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test
      
      - name: Rin lint
        run: npm run lint

  integration-tests:
    if: (startsWith( github.head_ref, 'ci/' ) || startsWith( github.head_ref, 'doc/' )) == false
    needs: unit-tests
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-db: test

      - name: Start Redis
        uses: supercharge/redis-github-action@1.6.0

      - name: Run tests
        run: npm run test:e2e -- --detectOpenHandles
        env:
          APP_NAME: 'AirBnB3'
          APP_PORT: 3000
          MONGODB_URI: 'mongodb://localhost:27017'
          MONGODB_DBNAME: 'test'
          JWT_SECRET: 'secret'
          JWT_ACCESS_EXPIRE: 1d
          JWT_REFRESH_EXPIRE: 7d
          TELEGRAM_SERVICE_DISABLED: true
          MAIL_SERVICE_DISABLED: true
            